dev:
  rabbit:
    host: "localhost"
    port: 5672
    virtualHost: "/"
    connectionName : "go publisher"
    username : "guest"
    password : "guest"
  mongo:
    connectionString : "mongodb://root:155202Asd...@localhost:27017"
    database :  "GoUsersDb"
    collection : {"Order" : "NewOrders" , "Product": "NewProducts"}
  kafka:
    producerConfig:
      bootstrap.Servers: pkc-6ojv2.us-west4.gcp.confluent.cloud:9092
      security.protocol: SASL_SSL
      sasl.mechanisms: PLAIN
      sasl.username: OV5JWHPDABXM6ULA
      sasl.password: hJMrMLFpri87uVgxVWfBeR7fCu+pNGIq/qTkEsrRDN2VB++I8VBKv2kkWAhQfz4g
      message.max.bytes: 1000
  orderKafka:
    orderCreated:
      topic: "orderCreatedTopic"
    orderUpdated:
      topic: "orderUpdatedTopic"
  order:
    orderCreated:
      exchange: "orderExchange"
      exchangeType: "topic"
      routingKey: "order.created"
      queue: "orderCreatedQueue"
    orderUpdated:
      exchange: "orderExchange"
      exchangeType: "topic"
      routingKey: "order.updated"
      queue: "orderUpdatedQueue"
  customerService:
    name : "CustomerService"
    baseUrl: "http://localhost:5000/"