dev:
  rabbit:
    host: "localhost"
    port: 5672
    virtualHost: "/"
    connectionName : "go publisher"
    username : "guest"
    password : "guest"
  mongo:
    connectionString : "mongodb://root:155202Asd...@localhost:27017"
    database :  "NewOrderDb"
    collection : {"Order" : "NewOrders" , "Product": "NewProducts"}
  kafka:
    configMap: {"server":"pkc-6ojv2.us-west4.gcp.confluent.cloud:9092", "acks" : "all"}
  orderKafka:
    orderCreated:
      topic: "orderCreatedTopic"
    orderUpdated:
      topic: "orderUpdatedTopic"
  order:
    orderCreated:
      exchange: "orderExchange"
      exchangeType: "topic"
      routingKey: "order.created"
      queue: "orderCreatedQueue"
    orderUpdated:
      exchange: "orderExchange"
      exchangeType: "topic"
      routingKey: "order.updated"
      queue: "orderUpdatedQueue"
  customerService:
    name : "CustomerService"
    baseUrl: "http://localhost:5000/"